"""Data models for the monitoring subsystem.

DetectedIssue  — raw fact from a V$/CDB_ view, no interpretation.
Recommendation — structured output the recommendation agent must return.
IssueRecord    — persisted incident lifecycle, recommendation, and ack state.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class IssueType(str, Enum):
    TABLESPACE_USAGE = "TABLESPACE_USAGE"
    BLOCKING_SESSION = "BLOCKING_SESSION"
    LONG_RUNNING_QUERY = "LONG_RUNNING_QUERY"
    ALERT_LOG_ERROR = "ALERT_LOG_ERROR"
    WAIT_EVENT = "WAIT_EVENT"
    WRITE_WORKLOAD = "WRITE_WORKLOAD"


class Severity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class IssueStatus(str, Enum):
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"


class StatusFilter(str, Enum):
    ALL = "ALL"
    ACTIVE = "ACTIVE"
    RESOLVED = "RESOLVED"


class AcknowledgmentFilter(str, Enum):
    ALL = "ALL"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    UNACKNOWLEDGED = "UNACKNOWLEDGED"


class SortOrder(str, Enum):
    NEWEST = "newest"
    OLDEST = "oldest"


class DetectedIssue(BaseModel):
    issue_type: IssueType
    severity: Severity
    summary: str
    details: dict[str, Any] = Field(default_factory=dict)
    diagnostics: dict[str, Any] = Field(default_factory=dict, exclude=True)
    detected_at: datetime = Field(default_factory=utcnow)

    def fingerprint(self) -> str:
        """Stable key used to dedupe repeated detections of the same problem.

        These keys intentionally preserve the Block 13 behavior so existing
        monitor.db rows continue matching after the Block 14 migration.
        """
        t = self.issue_type
        d = self.details
        if t == IssueType.TABLESPACE_USAGE:
            return f"{t.value}:{d.get('con_name')}:{d.get('tablespace_name')}"
        if t == IssueType.BLOCKING_SESSION:
            return f"{t.value}:{d.get('blocking_sid')}"
        if t == IssueType.LONG_RUNNING_QUERY:
            return f"{t.value}:{d.get('sid')}:{d.get('sql_id')}"
        if t == IssueType.ALERT_LOG_ERROR:
            return f"{t.value}:{d.get('message_hash')}"
        if t == IssueType.WAIT_EVENT:
            return f"{t.value}:{d.get('event')}"
        if t == IssueType.WRITE_WORKLOAD:
            return t.value
        return f"{t.value}:{self.summary}"


class ApprovedActionType(str, Enum):
    VERIFY = "VERIFY"
    REMEDIATION_TEMPLATE = "REMEDIATION_TEMPLATE"


class ApprovedAction(BaseModel):
    """Reviewed SQL displayed to the DBA; never generated by the LLM."""

    title: str
    action_type: ApprovedActionType
    sql: str
    requires_review: bool = False


class Recommendation(BaseModel):
    """Structured interpretation produced by the LLM agent.

    SQL and executable commands are intentionally excluded. Diagnostic SQL is
    owned by reviewed application code, not generated by the language model.
    """

    root_cause: str = Field(description="Likely root cause, in plain language.")
    recommended_action: str = Field(description="Concrete next step a DBA should take.")
    risk_if_ignored: str = Field(description="What happens if this is left unaddressed.")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence as a decimal from 0.0 through 1.0.",
    )


def fallback_recommendation(reason: str) -> Recommendation:
    """Used when the LLM call fails, so the issue is still recorded and visible."""
    return Recommendation(
        root_cause="Automated analysis unavailable.",
        recommended_action=f"Review manually — recommendation agent failed: {reason}",
        risk_if_ignored="Unknown until reviewed.",
        confidence=0.0,
    )


class IssueRecord(BaseModel):
    """What gets persisted to SQLite and served to the dashboard."""

    id: Optional[int] = None
    fingerprint: str
    issue_type: IssueType
    severity: Severity
    status: IssueStatus
    summary: str
    details: dict[str, Any]
    recommendation: Recommendation
    approved_actions: list[ApprovedAction] = Field(default_factory=list)
    detected_at: datetime
    last_seen_at: datetime
    resolved_at: Optional[datetime] = None
    recommendation_updated_at: datetime
    observation_count: int = 1
    episode_count: int = 1
    # Retained as a response compatibility alias for Block 13 clients.
    occurrence_count: int = 1
    acknowledged: bool = False
    acknowledged_by: Optional[str] = None
    acknowledged_at: Optional[datetime] = None
