CREATE TABLE app_ingest_demo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_worker NUMBER NOT NULL,
    event_key VARCHAR2(100) NOT NULL,
    payload VARCHAR2(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX app_ingest_demo_created_ix
    ON app_ingest_demo(created_at);
