#!/usr/bin/env python3
"""Simulate a fast message-ingest workload (like a RabbitMQ consumer) against Oracle.

Runs in the background and is controlled with start / stop / status commands,
so the monitor dashboard can be watched while load comes and goes.

Commands
    setup     Create the INGEST_SIM_ORDERS table (idempotent).
    start     Launch the load generator in the background.
    status    Show whether it is running, its phase, and live throughput.
    stop      Stop it gracefully (in-flight work is committed or rolled back).
    cleanup   Truncate (or --drop) the demo table.

Load modes
    steady    Constant load, optionally capped with --rate rows/sec.
    burst     Full load for --burst-seconds, idle for --pause-seconds, repeat.
    ramp      Start with --start-workers, add --step-workers every
              --step-seconds up to --workers. Optionally stop automatically
              once average commit latency exceeds --stop-latency-ms.

Commit modes
    row       One INSERT + COMMIT per message. This matches the existing
              RabbitMQ consumer and produces high commits/sec and
              'log file sync' waits - the classic "ingest is crawling" shape.
    batch     executemany() of --batch-size rows, one COMMIT per batch.
              Fewer commits, much more redo per second.

Examples (run from the project root)
    uv run --env-file .env.mcp --env-file .env.loadgen \\
        python scripts/ingest_simulator.py setup

    uv run --env-file .env.mcp --env-file .env.loadgen \\
        python scripts/ingest_simulator.py start --mode steady --workers 4 --rate 60

    uv run python scripts/ingest_simulator.py status
    uv run python scripts/ingest_simulator.py stop

Background mode is for Linux/macOS (POSIX signals, detached sessions). On
Windows use `start --foreground` and stop it with Ctrl+C or --duration;
`status` is safe there, but `stop` terminates the process without a
graceful shutdown (Oracle rolls back its open transactions).
"""

from __future__ import annotations

import argparse
import json
import os
import random
import signal
import string
import subprocess
import sys
import threading
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

TABLE_NAME = "INGEST_SIM_ORDERS"
MODULE_NAME = "ingest_simulator"
PRIVILEGED_USERS = {"SYS", "SYSTEM"}
MAX_CONSECUTIVE_ERRORS = 25

RUNTIME_DIR = Path(os.environ.get("INGEST_SIM_RUNTIME_DIR", PROJECT_ROOT / ".ingest_sim"))
PID_FILE = RUNTIME_DIR / "ingest_sim.pid"
STATE_FILE = RUNTIME_DIR / "ingest_sim.state.json"
LOG_FILE = RUNTIME_DIR / "ingest_sim.log"

DDL_STATEMENTS = [
    f"""
    CREATE TABLE {TABLE_NAME} (
        ID               NUMBER GENERATED BY DEFAULT AS IDENTITY,
        MESSAGE_ID       VARCHAR2(36)    NOT NULL,
        CUSTOMER_NAME    VARCHAR2(100)   NOT NULL,
        PRODUCT_NAME     VARCHAR2(100)   NOT NULL,
        QUANTITY         NUMBER(10)      NOT NULL,
        UNIT_PRICE       NUMBER(12, 2)   NOT NULL,
        ORDER_STATUS     VARCHAR2(20)    NOT NULL,
        SOURCE_WORKER    NUMBER(5)       NOT NULL,
        MESSAGE_PAYLOAD  VARCHAR2(4000)  NOT NULL,
        CREATED_AT       TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_INGEST_SIM_ORDERS PRIMARY KEY (ID),
        CONSTRAINT UQ_INGEST_SIM_MESSAGE_ID UNIQUE (MESSAGE_ID),
        CONSTRAINT CHK_INGEST_SIM_QTY_POS CHECK (QUANTITY > 0)
    )
    """,
    # Monotonically increasing key under concurrent inserts: a realistic
    # source of right-hand index contention in real ingest systems.
    f"CREATE INDEX IDX_INGEST_SIM_CREATED_AT ON {TABLE_NAME} (CREATED_AT)",
]

INSERT_SQL = f"""
INSERT INTO {TABLE_NAME} (
    MESSAGE_ID, CUSTOMER_NAME, PRODUCT_NAME, QUANTITY,
    UNIT_PRICE, ORDER_STATUS, SOURCE_WORKER, MESSAGE_PAYLOAD
) VALUES (
    :1, :2, :3, :4, :5, :6, :7, :8
)
"""

CUSTOMERS = ["Acme Corp", "Globex", "Initech", "Umbrella", "Hooli", "Stark Industries"]
PRODUCTS = ["Widget", "Gadget", "Sprocket", "Gizmo", "Doohickey"]
STATUSES = ["NEW", "NEW", "NEW", "PAID", "SHIPPED"]


# ---------------------------------------------------------------------------
# Small helpers
# ---------------------------------------------------------------------------


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def log(message: str) -> None:
    print(f"[{utc_now()}] {message}", flush=True)


def write_json_atomic(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, default=str))
    os.replace(tmp, path)


def read_json(path: Path) -> dict[str, Any] | None:
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def read_pid() -> int | None:
    try:
        return int(PID_FILE.read_text().strip())
    except (OSError, ValueError):
        return None


def _windows_process_alive(pid: int) -> bool:
    """Whether pid is a running process, without signalling it.

    On Windows os.kill(pid, 0) is not a probe: it TERMINATES the process.
    """
    import ctypes

    process_query_limited_information = 0x1000
    still_active = 259
    kernel32 = ctypes.windll.kernel32
    handle = kernel32.OpenProcess(process_query_limited_information, False, pid)
    if not handle:
        return False
    try:
        code = ctypes.c_ulong()
        if not kernel32.GetExitCodeProcess(handle, ctypes.byref(code)):
            return False
        return code.value == still_active
    finally:
        kernel32.CloseHandle(handle)


def is_our_process(pid: int) -> bool:
    """True if pid is alive and is this simulator (guards against PID reuse)."""
    if os.name == "nt":
        # No command line to check here: trust a live PID, as on macOS.
        return _windows_process_alive(pid)
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return False
    cmdline = Path(f"/proc/{pid}/cmdline")
    if cmdline.exists():
        try:
            text = cmdline.read_bytes().replace(b"\0", b" ").decode(errors="ignore")
        except OSError:
            return True
        return "ingest_simulator" in text and (" _run" in text or " start" in text)
    return True  # No /proc (macOS): trust the live PID.


def running_pid() -> int | None:
    pid = read_pid()
    if pid is not None and is_our_process(pid):
        return pid
    return None


def tail(path: Path, lines: int = 15) -> str:
    try:
        return "\n".join(path.read_text(errors="ignore").splitlines()[-lines:])
    except OSError:
        return "(no log output)"


# ---------------------------------------------------------------------------
# Oracle connection (real or dry-run)
# ---------------------------------------------------------------------------


def oracle_user() -> str:
    return os.environ.get("LOADGEN_ORACLE_USER") or os.environ.get("ORACLE_USER", "")


def guard_privileged_user(args: argparse.Namespace) -> None:
    if args.dry_run:
        return
    user = oracle_user().strip().upper()
    if user in PRIVILEGED_USERS and not args.allow_privileged_user:
        sys.exit(
            f"Refusing to run as {user}: the demo table would be created in the "
            f"{user} schema and could fill the SYSTEM tablespace.\n"
            "Create a dedicated user with scripts/ingest_simulator_user.sql and set "
            "LOADGEN_ORACLE_USER / LOADGEN_ORACLE_PASSWORD (e.g. in .env.loadgen).\n"
            "To override anyway, pass --allow-privileged-user."
        )


class _FakeCursor:
    """Dry-run cursor: simulates insert cost without a database."""

    def setinputsizes(self, *args: Any) -> None:
        pass

    def execute(self, sql: str, params: Any = None) -> None:
        time.sleep(0.0005)

    def executemany(self, sql: str, rows: list[Any]) -> None:
        time.sleep(0.0002 * len(rows))

    def close(self) -> None:
        pass


class _FakeConnection:
    module = action = client_identifier = ""

    def cursor(self) -> _FakeCursor:
        return _FakeCursor()

    def commit(self) -> None:
        time.sleep(0.001)

    def rollback(self) -> None:
        pass

    def close(self) -> None:
        pass


def connect(args: argparse.Namespace, action: str) -> Any:
    if args.dry_run:
        return _FakeConnection()

    import oracledb

    from oracle_core.config import get_settings
    from oracle_core.db import build_dsn

    settings = get_settings()
    user = os.environ.get("LOADGEN_ORACLE_USER") or settings.oracle_user
    password = (
        os.environ.get("LOADGEN_ORACLE_PASSWORD")
        or settings.oracle_password.get_secret_value()
    )
    database = args.database or settings.oracle_default_pdb_name
    connection = oracledb.connect(
        user=user,
        password=password,
        dsn=build_dsn(database),
        tcp_connect_timeout=10,
    )
    # Visible in V$SESSION.MODULE / ACTION so the agent and DBAs can spot it.
    connection.module = MODULE_NAME
    connection.action = action
    connection.client_identifier = f"ingest_sim:{os.getpid()}"
    return connection


# ---------------------------------------------------------------------------
# Runtime state shared by workers, controller and reporter
# ---------------------------------------------------------------------------


@dataclass
class Metrics:
    lock: threading.Lock = field(default_factory=threading.Lock)
    rows: int = 0
    commits: int = 0
    errors: int = 0
    commit_seconds: float = 0.0
    last_error: str | None = None

    def add(self, rows: int, commit_seconds: float) -> None:
        with self.lock:
            self.rows += rows
            self.commits += 1
            self.commit_seconds += commit_seconds

    def add_error(self, exc: BaseException) -> None:
        with self.lock:
            self.errors += 1
            self.last_error = f"{type(exc).__name__}: {str(exc)[:300]}"

    def snapshot(self) -> tuple[int, int, int, float, str | None]:
        with self.lock:
            return self.rows, self.commits, self.errors, self.commit_seconds, self.last_error


class Controller:
    """Decides which workers are active, based on the load mode."""

    def __init__(self, max_workers: int) -> None:
        self.max_workers = max_workers
        self.active_workers = 0
        self.paused = False
        self.phase = "starting"
        self._cond = threading.Condition()

    def set(self, *, active: int | None = None, paused: bool | None = None, phase: str | None = None) -> None:
        with self._cond:
            if active is not None:
                self.active_workers = max(0, min(active, self.max_workers))
            if paused is not None:
                self.paused = paused
            if phase is not None:
                self.phase = phase
            self._cond.notify_all()

    def is_active(self, worker_index: int) -> bool:
        return not self.paused and worker_index < self.active_workers

    def wait_for_change(self, timeout: float) -> None:
        with self._cond:
            self._cond.wait(timeout)

    def effective_active(self) -> int:
        return 0 if self.paused else self.active_workers


# ---------------------------------------------------------------------------
# Worker: one Oracle session each, like one consumer instance
# ---------------------------------------------------------------------------


def make_row(worker_id: int, payload_bytes: int) -> tuple[Any, ...]:
    message_id = str(uuid.uuid4())
    customer = random.choice(CUSTOMERS)
    product = random.choice(PRODUCTS)
    quantity = random.randint(1, 20)
    price = round(random.uniform(5, 500), 2)
    status = random.choice(STATUSES)
    body = json.dumps(
        {"message_id": message_id, "customer_name": customer, "product_name": product,
         "quantity": quantity, "unit_price": price, "order_status": status}
    )
    pad = max(0, payload_bytes - len(body))
    payload = body + "".join(random.choices(string.ascii_letters, k=pad))
    return (message_id, customer, product, quantity, price, status, worker_id, payload[:4000])


def run_worker(
    index: int,
    args: argparse.Namespace,
    controller: Controller,
    metrics: Metrics,
    stop_event: threading.Event,
) -> None:
    worker_id = index + 1
    connection = None
    cursor = None
    consecutive_errors = 0
    next_due = time.monotonic()

    try:
        while not stop_event.is_set():
            if not controller.is_active(index):
                if connection is not None and args.disconnect_when_idle:
                    connection.close()
                    connection = cursor = None
                controller.wait_for_change(0.5)
                next_due = time.monotonic()
                continue

            try:
                if connection is None:
                    connection = connect(args, action=f"{args.mode}:{args.commit_mode}")
                    cursor = connection.cursor()

                if args.commit_mode == "row":
                    cursor.execute(INSERT_SQL, make_row(worker_id, args.payload_bytes))
                    rows = 1
                else:
                    batch = [make_row(worker_id, args.payload_bytes) for _ in range(args.batch_size)]
                    cursor.executemany(INSERT_SQL, batch)
                    rows = len(batch)

                t0 = time.perf_counter()
                connection.commit()
                metrics.add(rows, time.perf_counter() - t0)
                consecutive_errors = 0

            except Exception as exc:  # keep running through transient Oracle errors
                metrics.add_error(exc)
                consecutive_errors += 1
                log(f"worker {worker_id}: {type(exc).__name__}: {str(exc)[:200]}")
                try:
                    if connection is not None:
                        connection.rollback()
                except Exception:
                    try:
                        connection.close()
                    except Exception:
                        pass
                    connection = cursor = None
                if consecutive_errors >= MAX_CONSECUTIVE_ERRORS:
                    log(f"worker {worker_id}: {consecutive_errors} consecutive errors, giving up")
                    return
                stop_event.wait(min(2 ** min(consecutive_errors, 4) * 0.25, 5.0))
                continue

            # Optional global rate cap, shared evenly across active workers.
            if args.rate > 0:
                active = max(controller.effective_active(), 1)
                per_worker = args.rate / active
                next_due += rows / per_worker
                delay = next_due - time.monotonic()
                if delay > 0:
                    stop_event.wait(delay)
                elif delay < -1.0:
                    next_due = time.monotonic()  # fell behind; don't try to catch up
    finally:
        if connection is not None:
            try:
                connection.rollback()
                connection.close()
            except Exception:
                pass


# ---------------------------------------------------------------------------
# Reporter: progress log + state file for `status`
# ---------------------------------------------------------------------------


class Reporter(threading.Thread):
    def __init__(self, args, controller, metrics, stop_event, started_wall, deadline_wall):
        super().__init__(name="ingest-sim-reporter", daemon=True)
        self.args = args
        self.controller = controller
        self.metrics = metrics
        self.stop_event = stop_event
        self.started_wall = started_wall
        self.deadline_wall = deadline_wall
        self.last = (time.monotonic(), 0, 0, 0.0)
        self.interval_rate = 0.0
        self.interval_commit_rate = 0.0
        self.interval_commit_ms = 0.0
        self.status = "running"

    def sample(self) -> None:
        now = time.monotonic()
        rows, commits, _, commit_s, _ = self.metrics.snapshot()
        t_prev, r_prev, c_prev, cs_prev = self.last
        dt = max(now - t_prev, 1e-3)
        dc = commits - c_prev
        self.interval_rate = (rows - r_prev) / dt
        self.interval_commit_rate = dc / dt
        self.interval_commit_ms = ((commit_s - cs_prev) / dc * 1000) if dc else 0.0
        self.last = (now, rows, commits, commit_s)

    def state(self) -> dict[str, Any]:
        rows, commits, errors, commit_s, last_error = self.metrics.snapshot()
        elapsed = max(time.time() - self.started_wall, 1e-3)
        return {
            "status": self.status,
            "pid": os.getpid(),
            "mode": self.args.mode,
            "commit_mode": self.args.commit_mode,
            "phase": self.controller.phase,
            "active_workers": self.controller.effective_active(),
            "max_workers": self.args.workers,
            "rows_per_sec": round(self.interval_rate, 1),
            "commits_per_sec": round(self.interval_commit_rate, 1),
            "avg_commit_ms": round(self.interval_commit_ms, 2),
            "rows_total": rows,
            "commits_total": commits,
            "errors_total": errors,
            "avg_rows_per_sec_overall": round(rows / elapsed, 1),
            "last_error": last_error,
            "started_at": datetime.fromtimestamp(self.started_wall, timezone.utc).isoformat(timespec="seconds"),
            "ends_at": (
                datetime.fromtimestamp(self.deadline_wall, timezone.utc).isoformat(timespec="seconds")
                if self.deadline_wall else "when stopped"
            ),
            "updated_at": utc_now(),
            "dry_run": self.args.dry_run,
            "config": {
                k: getattr(self.args, k)
                for k in ("database", "workers", "rate", "batch_size", "payload_bytes", "duration",
                          "burst_seconds", "pause_seconds", "start_workers", "step_workers",
                          "step_seconds", "stop_latency_ms")
            },
        }

    def publish(self, log_line: bool = True) -> None:
        self.sample()
        write_json_atomic(STATE_FILE, self.state())
        if log_line:
            rows, commits, errors, _, _ = self.metrics.snapshot()
            log(
                f"phase={self.controller.phase} active={self.controller.effective_active()}/"
                f"{self.args.workers} rows/s={self.interval_rate:,.0f} commits/s="
                f"{self.interval_commit_rate:,.0f} commit_ms={self.interval_commit_ms:.2f} "
                f"rows={rows:,} errors={errors}"
            )

    def run(self) -> None:
        while not self.stop_event.wait(self.args.report_every):
            self.publish()


# ---------------------------------------------------------------------------
# The background run: mode scheduling
# ---------------------------------------------------------------------------


def run_load(args: argparse.Namespace) -> int:
    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    PID_FILE.write_text(str(os.getpid()))

    stop_event = threading.Event()
    stop_requested = threading.Event()

    def on_signal(signum: int, _frame: Any) -> None:
        log(f"received {signal.Signals(signum).name}, stopping")
        stop_requested.set()
        stop_event.set()

    signal.signal(signal.SIGTERM, on_signal)
    signal.signal(signal.SIGINT, on_signal)

    controller = Controller(args.workers)
    metrics = Metrics()
    started_wall = time.time()
    started = time.monotonic()
    deadline = started + args.duration if args.duration > 0 else None
    deadline_wall = started_wall + args.duration if args.duration > 0 else None

    reporter = Reporter(args, controller, metrics, stop_event, started_wall, deadline_wall)
    exit_reason = "duration reached"

    log(
        f"starting mode={args.mode} commit_mode={args.commit_mode} workers={args.workers} "
        f"rate={'unlimited' if args.rate == 0 else args.rate} duration="
        f"{args.duration or 'until stopped'}s dry_run={args.dry_run}"
    )

    # Fail fast on bad credentials/connectivity before spawning workers.
    try:
        probe = connect(args, action="probe")
        probe.close()
    except Exception as exc:
        metrics.add_error(exc)
        reporter.status = "failed"
        write_json_atomic(STATE_FILE, reporter.state())
        log(f"cannot connect to Oracle: {exc}")
        PID_FILE.unlink(missing_ok=True)
        return 2

    workers = [
        threading.Thread(
            target=run_worker, args=(i, args, controller, metrics, stop_event),
            name=f"ingest-worker-{i + 1}", daemon=True,
        )
        for i in range(args.workers)
    ]
    for w in workers:
        w.start()
    reporter.start()

    try:
        if args.mode == "steady":
            controller.set(active=args.workers, phase="steady")

        elif args.mode == "burst":
            cycle = 0
            controller.set(active=args.workers)
            while not stop_event.is_set():
                cycle += 1
                controller.set(paused=False, phase=f"burst #{cycle}")
                if stop_event.wait(_bounded(args.burst_seconds, deadline)):
                    break
                if deadline and time.monotonic() >= deadline:
                    break
                controller.set(paused=True, phase=f"pause after burst #{cycle}")
                if stop_event.wait(_bounded(args.pause_seconds, deadline)):
                    break
                if deadline and time.monotonic() >= deadline:
                    break

        elif args.mode == "ramp":
            active = min(args.start_workers, args.workers)
            step = 1
            while not stop_event.is_set():
                controller.set(active=active, phase=f"ramp step {step} ({active} workers)")
                step_start = metrics.snapshot()
                if stop_event.wait(_bounded(args.step_seconds, deadline)):
                    break
                rows1, commits1, _, cs1, _ = metrics.snapshot()
                d_commits = commits1 - step_start[1]
                avg_ms = ((cs1 - step_start[3]) / d_commits * 1000) if d_commits else 0.0
                rate = (rows1 - step_start[0]) / args.step_seconds
                log(f"ramp step {step}: {active} workers -> {rate:,.0f} rows/s, avg commit {avg_ms:.2f} ms")
                if args.stop_latency_ms and avg_ms >= args.stop_latency_ms:
                    exit_reason = (f"saturation: avg commit {avg_ms:.1f} ms >= "
                                   f"{args.stop_latency_ms} ms at {active} workers")
                    log(exit_reason)
                    break
                if deadline and time.monotonic() >= deadline:
                    break
                if active >= args.workers:
                    controller.set(phase=f"holding at max ({active} workers)")
                    remaining = (deadline - time.monotonic()) if deadline else None
                    stop_event.wait(remaining)
                    break
                active = min(active + args.step_workers, args.workers)
                step += 1

        if args.mode == "steady":
            stop_event.wait((deadline - time.monotonic()) if deadline else None)

        if stop_requested.is_set():
            exit_reason = "stopped by request"

    finally:
        reporter.status = "stopping"
        controller.set(phase="stopping")
        stop_event.set()
        for w in workers:
            w.join(timeout=30)
        reporter.status = "stopped"
        controller.set(active=0, phase=f"stopped ({exit_reason})")
        reporter.publish(log_line=False)
        rows, commits, errors, _, _ = metrics.snapshot()
        log(f"stopped: {exit_reason}. rows={rows:,} commits={commits:,} errors={errors}")
        PID_FILE.unlink(missing_ok=True)

    return 0


def _bounded(seconds: float, deadline: float | None) -> float:
    if deadline is None:
        return seconds
    return max(0.0, min(seconds, deadline - time.monotonic()))


# ---------------------------------------------------------------------------
# CLI commands
# ---------------------------------------------------------------------------


def cmd_setup(args: argparse.Namespace) -> int:
    guard_privileged_user(args)
    if args.dry_run:
        print("dry-run: would create", TABLE_NAME)
        return 0
    import oracledb

    with connect(args, action="setup") as connection:
        with connection.cursor() as cursor:
            for ddl in DDL_STATEMENTS:
                try:
                    cursor.execute(ddl)
                except oracledb.DatabaseError as exc:
                    (error,) = exc.args
                    if error.code in (955, 1408):  # already exists / already indexed
                        continue
                    raise
    print(f"{TABLE_NAME} is ready in schema {oracle_user().upper()}.")
    return 0


def cmd_start(args: argparse.Namespace) -> int:
    guard_privileged_user(args)
    pid = running_pid()
    if pid:
        print(f"Already running (pid {pid}). Use 'status' or 'stop' first.")
        return 1

    if args.foreground:
        return run_load(args)

    RUNTIME_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.unlink(missing_ok=True)
    argv = sys.argv[1:]
    argv[argv.index("start")] = "_run"
    with open(LOG_FILE, "a") as log_handle:
        log_handle.write(f"\n===== start {utc_now()} =====\n")
        log_handle.flush()
        proc = subprocess.Popen(
            [sys.executable, str(Path(__file__).resolve()), *argv],
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            start_new_session=True,  # survives the terminal closing
            cwd=str(PROJECT_ROOT),
            env=os.environ.copy(),
        )

    # Give it a moment to connect so config/credential errors surface now.
    for _ in range(40):
        time.sleep(0.25)
        state = read_json(STATE_FILE)
        if proc.poll() is not None:
            print("Simulator exited during startup. Last log lines:\n")
            print(tail(LOG_FILE))
            return 1
        if state and state.get("status") == "running":
            break

    print(f"Started ingest simulator (pid {proc.pid}), mode={args.mode}, commit_mode={args.commit_mode}.")
    print(f"  log:    {LOG_FILE}")
    print("  status: python scripts/ingest_simulator.py status")
    print("  stop:   python scripts/ingest_simulator.py stop")
    return 0


def cmd_status(args: argparse.Namespace) -> int:
    pid = running_pid()
    state = read_json(STATE_FILE)

    if args.json:
        print(json.dumps({"running": bool(pid), "state": state}, indent=2, default=str))
        return 0 if pid else 3

    if not pid and not state:
        print("Not running. No previous run recorded.")
        return 3

    if pid:
        print(f"RUNNING (pid {pid})")
    else:
        print(f"NOT RUNNING - last run: {state.get('status') if state else 'unknown'}")
        if PID_FILE.exists():
            PID_FILE.unlink(missing_ok=True)  # stale pid file

    if state:
        rows = [
            ("mode", f"{state['mode']} / commit per {state['commit_mode']}"),
            ("phase", state["phase"]),
            ("workers", f"{state['active_workers']} active of {state['max_workers']}"),
            ("throughput", f"{state['rows_per_sec']:,} rows/s, {state['commits_per_sec']:,} commits/s"),
            ("avg commit", f"{state['avg_commit_ms']} ms"),
            ("totals", f"{state['rows_total']:,} rows, {state['commits_total']:,} commits, "
                       f"{state['errors_total']} errors"),
            ("started", state["started_at"]),
            ("ends", state["ends_at"]),
            ("updated", state["updated_at"]),
        ]
        if state.get("last_error"):
            rows.append(("last error", state["last_error"]))
        if state.get("dry_run"):
            rows.append(("note", "DRY RUN - no database was touched"))
        width = max(len(k) for k, _ in rows)
        for key, value in rows:
            print(f"  {key.ljust(width)}  {value}")
    return 0 if pid else 3


def cmd_stop(args: argparse.Namespace) -> int:
    pid = running_pid()
    if not pid:
        print("Not running.")
        PID_FILE.unlink(missing_ok=True)
        return 0

    print(f"Stopping pid {pid} ...")
    os.kill(pid, signal.SIGTERM)
    deadline = time.monotonic() + args.timeout
    while time.monotonic() < deadline:
        if not is_our_process(pid):
            break
        time.sleep(0.5)
    else:
        print(f"Did not stop within {args.timeout}s; sending SIGKILL "
              "(Oracle will roll back any open transactions).")
        os.kill(pid, signal.SIGKILL)
        PID_FILE.unlink(missing_ok=True)

    state = read_json(STATE_FILE) or {}
    print(f"Stopped. rows={state.get('rows_total', 0):,} commits={state.get('commits_total', 0):,} "
          f"errors={state.get('errors_total', 0)}")
    return 0


def cmd_cleanup(args: argparse.Namespace) -> int:
    guard_privileged_user(args)
    if running_pid():
        print("Simulator is running. Stop it first.")
        return 1
    action = "DROP" if args.drop else "TRUNCATE"
    if not args.yes:
        answer = input(f"{action} table {TABLE_NAME} in schema {oracle_user().upper()}? Type YES: ")
        if answer.strip() != "YES":
            print("Cancelled.")
            return 1
    if args.dry_run:
        print(f"dry-run: would {action} {TABLE_NAME}")
        return 0
    sql = f"DROP TABLE {TABLE_NAME} PURGE" if args.drop else f"TRUNCATE TABLE {TABLE_NAME}"
    with connect(args, action="cleanup") as connection:
        with connection.cursor() as cursor:
            cursor.execute(sql)
    print(f"{action} {TABLE_NAME} done.")
    return 0


# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------


def positive_int(value: str) -> int:
    number = int(value)
    if number <= 0:
        raise argparse.ArgumentTypeError("must be greater than zero")
    return number


def non_negative_float(value: str) -> float:
    number = float(value)
    if number < 0:
        raise argparse.ArgumentTypeError("must be zero or greater")
    return number


def add_connection_args(p: argparse.ArgumentParser) -> None:
    p.add_argument("--database", help="PDB/service name (default: ORACLE_DEFAULT_PDB_NAME).")
    p.add_argument("--dry-run", action="store_true", help="Simulate without connecting to Oracle.")
    p.add_argument("--allow-privileged-user", action="store_true",
                   help="Allow running as SYS/SYSTEM (not recommended).")


def add_load_args(p: argparse.ArgumentParser) -> None:
    add_connection_args(p)
    p.add_argument("--mode", choices=["steady", "burst", "ramp"], default="steady")
    p.add_argument("--commit-mode", choices=["row", "batch"], default="row",
                   help="row = commit per message (default), batch = commit per batch.")
    p.add_argument("--workers", type=positive_int, default=4,
                   help="Concurrent sessions; for ramp, the maximum (default: 4).")
    p.add_argument("--rate", type=non_negative_float, default=0,
                   help="Total target rows/sec across workers; 0 = as fast as possible.")
    p.add_argument("--batch-size", type=positive_int, default=200, help="Rows per commit in batch mode.")
    p.add_argument("--payload-bytes", type=positive_int, default=800, help="Approx bytes per row (max 4000).")
    p.add_argument("--duration", type=int, default=600,
                   help="Seconds before auto-stop (default 600). 0 = run until 'stop'.")
    p.add_argument("--report-every", type=positive_int, default=3, help="Seconds between status updates.")
    p.add_argument("--disconnect-when-idle", action="store_true",
                   help="Close sessions during pauses instead of leaving them idle.")
    g = p.add_argument_group("burst mode")
    g.add_argument("--burst-seconds", type=positive_int, default=45)
    g.add_argument("--pause-seconds", type=positive_int, default=60)
    g = p.add_argument_group("ramp mode")
    g.add_argument("--start-workers", type=positive_int, default=1)
    g.add_argument("--step-workers", type=positive_int, default=1)
    g.add_argument("--step-seconds", type=positive_int, default=30)
    g.add_argument("--stop-latency-ms", type=non_negative_float, default=0,
                   help="Auto-stop when average commit latency in a step reaches this. 0 = off.")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Simulate fast message ingest into Oracle (steady / burst / ramp).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("setup", help=f"Create {TABLE_NAME}.")
    add_connection_args(p)
    p.set_defaults(func=cmd_setup)

    p = sub.add_parser("start", help="Start the load in the background.")
    add_load_args(p)
    p.add_argument("--foreground", action="store_true", help="Run attached to this terminal.")
    p.set_defaults(func=cmd_start)

    p = sub.add_parser("_run", help=argparse.SUPPRESS)
    add_load_args(p)
    p.add_argument("--foreground", action="store_true", help=argparse.SUPPRESS)
    p.set_defaults(func=run_load)

    p = sub.add_parser("status", help="Show current status.")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=cmd_status)

    p = sub.add_parser("stop", help="Stop the background load.")
    p.add_argument("--timeout", type=positive_int, default=40)
    p.set_defaults(func=cmd_stop)

    p = sub.add_parser("cleanup", help=f"Truncate or drop {TABLE_NAME}.")
    add_connection_args(p)
    p.add_argument("--drop", action="store_true")
    p.add_argument("--yes", action="store_true")
    p.set_defaults(func=cmd_cleanup)

    return parser


def main() -> int:
    args = build_parser().parse_args()
    if getattr(args, "payload_bytes", 0) > 4000:
        sys.exit("--payload-bytes cannot exceed 4000 (VARCHAR2 column limit).")
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
