#!/usr/bin/env python3
"""Generate a controlled concurrent INSERT workload against Oracle.

The script reuses the project's ORACLE_* settings loaded from .env.mcp.
Each worker owns its own Oracle connection and inserts rows in batches.

Example:
    uv run --env-file .env.mcp python scripts/oracle_insert_load.py \
      --setup-table --workers 10 --batch-size 100 --duration 120
"""

from __future__ import annotations

import argparse
import concurrent.futures
import os
import random
import string
import threading
import time
from dataclasses import dataclass
from datetime import datetime, timezone

import oracledb
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from oracle_core.config import get_settings
from oracle_core.db import build_dsn

TABLE_NAME = "APP_INGEST_DEMO"
_INSERT_SQL = f"""
INSERT INTO {TABLE_NAME} (
    source_worker,
    event_key,
    payload,
    created_at
)
VALUES (
    :1,
    :2,
    :3,
    SYSTIMESTAMP
)
"""


@dataclass(frozen=True)
class WorkerResult:
    worker_id: int
    rows_inserted: int
    commits: int
    elapsed_seconds: float


class SharedCounters:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self.rows = 0
        self.commits = 0
        self.errors = 0

    def add_success(self, rows: int) -> None:
        with self._lock:
            self.rows += rows
            self.commits += 1

    def add_error(self) -> None:
        with self._lock:
            self.errors += 1

    def snapshot(self) -> tuple[int, int, int]:
        with self._lock:
            return self.rows, self.commits, self.errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a concurrent Oracle INSERT workload for monitoring demos."
    )
    parser.add_argument(
        "--database",
        help="Oracle service/PDB name. Defaults to ORACLE_DEFAULT_PDB_NAME.",
    )
    parser.add_argument(
        "--setup-table",
        action="store_true",
        help=f"Create {TABLE_NAME} and its index if they do not exist.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=5,
        help="Number of concurrent database sessions (default: 5).",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=100,
        help="Rows inserted per executemany() and commit (default: 100).",
    )
    parser.add_argument(
        "--duration",
        type=int,
        default=60,
        help="Workload duration in seconds (default: 60).",
    )
    parser.add_argument(
        "--payload-bytes",
        type=int,
        default=500,
        help="Approximate payload size per row (default: 500).",
    )
    parser.add_argument(
        "--report-every",
        type=int,
        default=5,
        help="Progress-report interval in seconds (default: 5).",
    )
    parser.add_argument(
        "--sleep-ms",
        type=float,
        default=0.0,
        help="Optional pause after each committed batch (default: 0).",
    )
    args = parser.parse_args()

    for name in ("workers", "batch_size", "duration", "payload_bytes", "report_every"):
        if getattr(args, name) <= 0:
            parser.error(f"--{name.replace('_', '-')} must be greater than zero")
    if args.sleep_ms < 0:
        parser.error("--sleep-ms must be zero or greater")
    return args


def connect(database_name: str) -> oracledb.Connection:
    settings = get_settings()
    connection = oracledb.connect(
        user=settings.oracle_user,
        password=settings.oracle_password.get_secret_value(),
        dsn=build_dsn(database_name),
    )
    connection.module = "oracle_insert_load"
    connection.action = "bulk_insert_demo"
    connection.client_identifier = f"loadgen:{os.getpid()}"
    return connection


def setup_table(database_name: str) -> None:
    statements = [
        f"""
        CREATE TABLE {TABLE_NAME} (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_worker NUMBER NOT NULL,
            event_key VARCHAR2(100) NOT NULL,
            payload VARCHAR2(4000) NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
        )
        """,
        f"CREATE INDEX APP_INGEST_DEMO_CREATED_IX ON {TABLE_NAME}(created_at)",
    ]

    with connect(database_name) as connection:
        with connection.cursor() as cursor:
            for statement in statements:
                try:
                    cursor.execute(statement)
                except oracledb.DatabaseError as exc:
                    error, = exc.args
                    if error.code == 955:  # ORA-00955: object already exists
                        continue
                    raise
        connection.commit()

    print(f"Table {TABLE_NAME} is ready in service {database_name}.")


def make_payload(size: int, worker_id: int) -> str:
    prefix = f"worker={worker_id};"
    remaining = max(0, size - len(prefix))
    alphabet = string.ascii_letters + string.digits
    return prefix + "".join(random.choices(alphabet, k=remaining))


def run_worker(
    *,
    worker_id: int,
    database_name: str,
    batch_size: int,
    payload_bytes: int,
    sleep_ms: float,
    stop_event: threading.Event,
    counters: SharedCounters,
) -> WorkerResult:
    started = time.monotonic()
    rows_inserted = 0
    commits = 0
    sequence = 0
    payload = make_payload(payload_bytes, worker_id)

    with connect(database_name) as connection:
        with connection.cursor() as cursor:
            cursor.setinputsizes(None, 100, payload_bytes)

            while not stop_event.is_set():
                rows = []
                now_ns = time.time_ns()
                for _ in range(batch_size):
                    sequence += 1
                    event_key = f"w{worker_id}-{now_ns}-{sequence}"
                    rows.append((worker_id, event_key, payload))

                try:
                    cursor.executemany(_INSERT_SQL, rows)
                    connection.commit()
                except Exception:
                    connection.rollback()
                    counters.add_error()
                    raise

                rows_inserted += len(rows)
                commits += 1
                counters.add_success(len(rows))

                if sleep_ms:
                    stop_event.wait(sleep_ms / 1000.0)

    return WorkerResult(
        worker_id=worker_id,
        rows_inserted=rows_inserted,
        commits=commits,
        elapsed_seconds=time.monotonic() - started,
    )


def report_progress(
    *,
    counters: SharedCounters,
    stop_event: threading.Event,
    report_every: int,
    started: float,
) -> None:
    previous_rows = 0
    previous_time = started

    while not stop_event.wait(report_every):
        now = time.monotonic()
        rows, commits, errors = counters.snapshot()
        interval = max(now - previous_time, 0.001)
        rate = (rows - previous_rows) / interval
        print(
            f"[{datetime.now(timezone.utc).isoformat(timespec='seconds')}] "
            f"rows={rows:,} commits={commits:,} errors={errors} "
            f"current_rate={rate:,.0f} rows/sec",
            flush=True,
        )
        previous_rows = rows
        previous_time = now


def main() -> int:
    args = parse_args()
    settings = get_settings()
    database_name = args.database or settings.oracle_default_pdb_name

    if args.setup_table:
        setup_table(database_name)

    print(
        "Starting Oracle insert load: "
        f"database={database_name}, workers={args.workers}, "
        f"batch_size={args.batch_size}, duration={args.duration}s, "
        f"payload={args.payload_bytes} bytes, sleep_ms={args.sleep_ms}"
    )

    counters = SharedCounters()
    stop_event = threading.Event()
    started = time.monotonic()

    reporter = threading.Thread(
        target=report_progress,
        kwargs={
            "counters": counters,
            "stop_event": stop_event,
            "report_every": args.report_every,
            "started": started,
        },
        name="load-progress-reporter",
        daemon=True,
    )
    reporter.start()

    futures: list[concurrent.futures.Future[WorkerResult]] = []
    try:
        with concurrent.futures.ThreadPoolExecutor(
            max_workers=args.workers,
            thread_name_prefix="oracle-load",
        ) as executor:
            for worker_id in range(1, args.workers + 1):
                futures.append(
                    executor.submit(
                        run_worker,
                        worker_id=worker_id,
                        database_name=database_name,
                        batch_size=args.batch_size,
                        payload_bytes=args.payload_bytes,
                        sleep_ms=args.sleep_ms,
                        stop_event=stop_event,
                        counters=counters,
                    )
                )

            stop_event.wait(args.duration)
            stop_event.set()

            results = [future.result() for future in futures]
    except KeyboardInterrupt:
        print("Stopping workload...")
        stop_event.set()
        results = [
            future.result()
            for future in futures
            if future.done() and not future.cancelled()
        ]
    finally:
        stop_event.set()
        reporter.join(timeout=2)

    elapsed = max(time.monotonic() - started, 0.001)
    total_rows, total_commits, total_errors = counters.snapshot()
    print("\nWorkload complete")
    print(f"  elapsed:       {elapsed:.1f} seconds")
    print(f"  rows inserted: {total_rows:,}")
    print(f"  commits:       {total_commits:,}")
    print(f"  errors:        {total_errors:,}")
    print(f"  average rate:  {total_rows / elapsed:,.0f} rows/sec")
    print(f"  workers ended: {len(results)}/{args.workers}")
    return 0 if total_errors == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
